### ISSUE TITLE
Running  srum_dump2.py in WSL

### ISSUE THREAD

**Issue by dfir-scripts** [MarkBaggett/srum-dump#35]
By default WSL has no GUI so tkinker cannot be installed or load
Was able to bypass and run successfully with the  "-q" switch by commenting out the line
"import PySimpleGUI as sg"

So perhaps this is more of a feature request than a bug.   

command: 
python srum_dump2.py -q -i /mnt/c/temp/SRUDB.dat -t SRUM_TEMPLATE2.xlsx -o /mnt/c/temp/sru1.xlsx

error:
Traceback (most recent call last):
  File "srum_dump2.py", line 19, in <module>
    import PySimpleGUI as sg
  File "/usr/local/lib/python3.8/dist-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/usr/local/lib/python3.8/dist-packages/PySimpleGUI/PySimpleGUI.py", line 136, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by MarkBaggett** [comment]
Srum-dump is a GUI based tool.  If you are interested in a command line version you should check out ese-analyst. https://github.com/MarkBaggett/ese-analyst

Mark
________________________________
From: jbrown ***@***.***>
Sent: Tuesday, October 18, 2022 2:15:33 PM
To: MarkBaggett/srum-dump ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MarkBaggett/srum-dump] Running srum_dump2.py in WSL (Issue #35)


By default WSL has no GUI so tkinker cannot be installed or load
Was able to bypass and run successfully with the "-q" switch by commenting out the line
"import PySimpleGUI as sg"

So perhaps this is more of a feature request than a bug.

command:
python srum_dump2.py -q -i /mnt/c/temp/SRUDB.dat -t SRUM_TEMPLATE2.xlsx -o /mnt/c/temp/sru1.xlsx

error:
Traceback (most recent call last):
File "srum_dump2.py", line 19, in
import PySimpleGUI as sg
File "/usr/local/lib/python3.8/dist-packages/PySimpleGUI/init.py", line 2, in
from .PySimpleGUI import *
File "/usr/local/lib/python3.8/dist-packages/PySimpleGUI/PySimpleGUI.py", line 136, in
import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by dfir-scripts** [comment]
Thanks!  will check it out
